CREATE TABLE IF NOT EXISTS account(
    txId BIGINT(19) AUTO_INCREMENT PRIMARY KEY,
    fromAccountId BIGINT(19) NOT NULL,
    toAccountId BIGINT(19) NOT NULL,
    amount DOUBLE NOT NULL
)  ENGINE=INNODB;